# Generated by Django 5.2.7 on 2025-10-22 20:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_keypersonnel"),
        ("core", "0002_trainingsyllabus_trainingregister"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RPASOperationsManual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manual_id",
                    models.CharField(
                        help_text="Format: OPS-YYYY-XXX (e.g., OPS-2025-001)",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Format: XXX-YYYY-XXX",
                                regex="^(OPS|MNT|TRN|EMG|SMS|QUA)-\\d{4}-\\d{3}$",
                            )
                        ],
                        verbose_name="Manual ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Complete title of operations manual",
                        max_length=200,
                        verbose_name="Manual Title",
                    ),
                ),
                (
                    "manual_type",
                    models.CharField(
                        choices=[
                            ("operations", "Operations Manual"),
                            ("maintenance", "Maintenance Manual"),
                            ("training", "Training Manual"),
                            ("emergency", "Emergency Procedures Manual"),
                            ("safety", "Safety Management System Manual"),
                            ("quality", "Quality Assurance Manual"),
                        ],
                        help_text="Type of operations manual",
                        max_length=20,
                        verbose_name="Manual Type",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Version number (e.g., 1.0, 2.1)",
                        max_length=10,
                        verbose_name="Version",
                    ),
                ),
                (
                    "revision_number",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Sequential revision number",
                        verbose_name="Revision Number",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        help_text="Date manual becomes effective",
                        verbose_name="Effective Date",
                    ),
                ),
                (
                    "next_review_date",
                    models.DateField(
                        help_text="Required review date - typically annual",
                        verbose_name="Next Review Date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Under Review"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("superseded", "Superseded"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Document Status",
                    ),
                ),
                (
                    "casa_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Manual approved by CASA",
                        verbose_name="CASA Approved",
                    ),
                ),
                (
                    "casa_approval_reference",
                    models.CharField(
                        blank=True,
                        help_text="CASA approval or acceptance reference number",
                        max_length=100,
                        verbose_name="CASA Approval Reference",
                    ),
                ),
                (
                    "casa_approval_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of CASA approval",
                        null=True,
                        verbose_name="CASA Approval Date",
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        default="Drone Ultra Images",
                        help_text="Operating organization name",
                        max_length=200,
                        verbose_name="Organization Name",
                    ),
                ),
                (
                    "reoc_number",
                    models.CharField(
                        blank=True,
                        help_text="Remote Operator Certificate number if applicable",
                        max_length=50,
                        verbose_name="ReOC Number",
                    ),
                ),
                (
                    "approval_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of organizational approval",
                        null=True,
                        verbose_name="Approval Date",
                    ),
                ),
                (
                    "purpose",
                    models.TextField(
                        help_text="Purpose of manual and operational scope",
                        verbose_name="Purpose and Scope",
                    ),
                ),
                (
                    "abstract",
                    models.TextField(
                        help_text="Brief summary of manual contents and applicability",
                        verbose_name="Abstract",
                    ),
                ),
                (
                    "applicable_regulations",
                    models.TextField(
                        default="CASA Part 101 - Unmanned Aircraft and Rocket Operations",
                        help_text="Primary regulatory framework",
                        verbose_name="Applicable Regulations",
                    ),
                ),
                (
                    "change_summary",
                    models.TextField(
                        blank=True,
                        help_text="Summary of changes from previous version",
                        verbose_name="Change Summary",
                    ),
                ),
                (
                    "supersedes_version",
                    models.CharField(
                        blank=True,
                        help_text="Previous version that this manual supersedes",
                        max_length=10,
                        verbose_name="Supersedes Version",
                    ),
                ),
                (
                    "controlled_distribution",
                    models.BooleanField(
                        default=True,
                        help_text="Manual requires controlled distribution",
                        verbose_name="Controlled Distribution",
                    ),
                ),
                (
                    "digital_signature_required",
                    models.BooleanField(
                        default=True,
                        help_text="Requires digital signatures for approval",
                        verbose_name="Digital Signature Required",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Key personnel who approved manual (typically CRP or Head of Operations)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manuals_approved",
                        to="accounts.keypersonnel",
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        help_text="Person who prepared the manual",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manuals_prepared",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Prepared By",
                    ),
                ),
                (
                    "related_sops",
                    models.ManyToManyField(
                        blank=True,
                        help_text="SOPs incorporated or referenced in this manual",
                        to="core.standardoperatingprocedure",
                        verbose_name="Related SOPs",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person who reviewed the manual",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manuals_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
                (
                    "training_syllabus",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Training syllabi covered by this manual",
                        to="core.trainingsyllabus",
                        verbose_name="Training Syllabus",
                    ),
                ),
            ],
            options={
                "verbose_name": "RPAS Operations Manual",
                "verbose_name_plural": "RPAS Operations Manuals",
                "ordering": ["-version", "-revision_number"],
            },
        ),
        migrations.CreateModel(
            name="ManualSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_number",
                    models.CharField(
                        help_text="Section number (e.g., 1, 2, 3, A, B)",
                        max_length=10,
                        verbose_name="Section Number",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Descriptive title of section",
                        max_length=200,
                        verbose_name="Section Title",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("operational", "Operational Procedures"),
                            ("emergency", "Emergency Procedures"),
                            ("safety", "Safety Management"),
                            ("training", "Training and Competency"),
                            ("maintenance", "Maintenance"),
                            ("quality", "Quality Assurance"),
                            ("appendix", "Appendix"),
                        ],
                        help_text="Category of section content",
                        max_length=20,
                        verbose_name="Section Type",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Order for display in manual",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Main content of section (supports HTML/Markdown)",
                        verbose_name="Section Content",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_sops",
                    models.ManyToManyField(
                        blank=True,
                        help_text="SOPs detailed in this section",
                        to="core.standardoperatingprocedure",
                        verbose_name="Related SOPs",
                    ),
                ),
                (
                    "required_training",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Training requirements covered in this section",
                        to="core.trainingsyllabus",
                        verbose_name="Required Training",
                    ),
                ),
                (
                    "operations_manual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="core.rpasoperationsmanual",
                        verbose_name="Operations Manual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manual Section",
                "verbose_name_plural": "Manual Sections",
                "ordering": ["operations_manual", "order", "section_number"],
                "unique_together": {("operations_manual", "section_number")},
            },
        ),
        migrations.CreateModel(
            name="ManualApprovalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Document Created"),
                            ("reviewed", "Reviewed"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("revised", "Revised"),
                            ("superseded", "Superseded"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "action_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Action Date"),
                ),
                (
                    "version_at_action",
                    models.CharField(
                        help_text="Document version when action was performed",
                        max_length=10,
                        verbose_name="Version at Action",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True,
                        help_text="Comments or notes about the action",
                        verbose_name="Comments",
                    ),
                ),
                (
                    "digital_signature",
                    models.CharField(
                        blank=True,
                        help_text="Digital signature hash or reference",
                        max_length=500,
                        verbose_name="Digital Signature",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of user performing action",
                        null=True,
                        verbose_name="IP Address",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Performed By",
                    ),
                ),
                (
                    "operations_manual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_history",
                        to="core.rpasoperationsmanual",
                        verbose_name="Operations Manual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manual Approval History",
                "verbose_name_plural": "Manual Approval Histories",
                "ordering": ["-action_date"],
            },
        ),
        migrations.CreateModel(
            name="ManualSubsection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subsection_number",
                    models.CharField(
                        help_text="Subsection number (e.g., 1.1, 1.2, A.1)",
                        max_length=10,
                        verbose_name="Subsection Number",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Subsection Title"),
                ),
                ("order", models.PositiveIntegerField(verbose_name="Display Order")),
                (
                    "content",
                    models.TextField(
                        help_text="Detailed content (supports HTML/Markdown)",
                        verbose_name="Subsection Content",
                    ),
                ),
                (
                    "casa_reference",
                    models.CharField(
                        blank=True,
                        help_text="Specific CASA regulation reference (e.g., 101.073)",
                        max_length=50,
                        verbose_name="CASA Reference",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsections",
                        to="core.manualsection",
                        verbose_name="Parent Section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manual Subsection",
                "verbose_name_plural": "Manual Subsections",
                "ordering": ["section", "order", "subsection_number"],
                "unique_together": {("section", "subsection_number")},
            },
        ),
        migrations.CreateModel(
            name="ManualDistributionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distribution_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Distribution Date"
                    ),
                ),
                (
                    "version_distributed",
                    models.CharField(max_length=10, verbose_name="Version Distributed"),
                ),
                (
                    "acknowledgment_required",
                    models.BooleanField(
                        default=True,
                        help_text="Recipient must acknowledge receipt",
                        verbose_name="Acknowledgment Required",
                    ),
                ),
                (
                    "acknowledged_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date recipient acknowledged receipt",
                        null=True,
                        verbose_name="Acknowledged Date",
                    ),
                ),
                (
                    "access_revoked",
                    models.BooleanField(default=False, verbose_name="Access Revoked"),
                ),
                (
                    "revocation_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Revocation Date"
                    ),
                ),
                (
                    "access_granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manual_distributions_granted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Access Granted By",
                    ),
                ),
                (
                    "distributed_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Distributed To",
                    ),
                ),
                (
                    "operations_manual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_records",
                        to="core.rpasoperationsmanual",
                        verbose_name="Operations Manual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manual Distribution Record",
                "verbose_name_plural": "Manual Distribution Records",
                "ordering": ["-distribution_date"],
                "unique_together": {
                    ("operations_manual", "distributed_to", "version_distributed")
                },
            },
        ),
    ]
