# Generated by Django 5.2.7 on 2025-10-22 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rpas_operations_manual"),
        ("flight_operations", "0002_remove_mission_risk_assessment_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sopriskassessment",
            name="risk_register",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated risk register entry from flight operations",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="flight_operations.riskregister",
                verbose_name="Risk Register Entry",
            ),
        ),
    ]
