# Generated by Django 5.2.7 on 2025-10-22 10:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AirspaceClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "airspace_class",
                    models.CharField(
                        choices=[
                            ("A", "Class A - Controlled Airspace"),
                            ("C", "Class C - Controlled Airspace"),
                            ("D", "Class D - Controlled Airspace"),
                            ("E", "Class E - Controlled Airspace"),
                            ("G", "Class G - Uncontrolled Airspace"),
                        ],
                        help_text="CASA airspace classification",
                        max_length=1,
                        unique=True,
                        verbose_name="Airspace Class",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for airspace class",
                        max_length=100,
                        verbose_name="Class Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of airspace class characteristics",
                        verbose_name="Description",
                    ),
                ),
                (
                    "authorization_level",
                    models.CharField(
                        choices=[
                            ("prohibited", "Prohibited - No RPA Operations"),
                            ("casa_approval", "CASA Approval Required"),
                            ("atc_clearance", "ATC Clearance Required"),
                            ("notification", "Notification Required"),
                            ("restricted", "Restricted Operations"),
                            ("unrestricted", "Unrestricted (Subject to Part 101)"),
                        ],
                        help_text="Required authorization level for RPA operations",
                        max_length=20,
                        verbose_name="Authorization Level",
                    ),
                ),
                (
                    "maximum_height_agl",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum operating height above ground level",
                        null=True,
                        verbose_name="Maximum Height AGL (feet)",
                    ),
                ),
                (
                    "excluded_category_allowed",
                    models.BooleanField(
                        default=False,
                        help_text="Excluded category RPA operations permitted",
                        verbose_name="Excluded Category Allowed",
                    ),
                ),
                (
                    "pilot_license_required",
                    models.CharField(
                        choices=[
                            ("none", "None Required"),
                            ("reoc", "ReOC Required"),
                            ("rpl", "Remote Pilot License"),
                            ("cpl", "Commercial Pilot License"),
                        ],
                        default="none",
                        help_text="Minimum pilot qualification required",
                        max_length=20,
                        verbose_name="Pilot License Required",
                    ),
                ),
                (
                    "casa_regulation_reference",
                    models.CharField(
                        blank=True,
                        help_text="Relevant CASA regulation or order",
                        max_length=100,
                        verbose_name="CASA Regulation Reference",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Airspace Class",
                "verbose_name_plural": "Airspace Classes",
                "ordering": ["airspace_class"],
            },
        ),
        migrations.CreateModel(
            name="OperationalArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area_id",
                    models.CharField(
                        help_text="Unique identifier for operational area",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Format: OA-XXXXXX (6-12 alphanumeric characters)",
                                regex="^OA-[A-Z0-9]{6,12}$",
                            )
                        ],
                        verbose_name="Area ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for operational area",
                        max_length=100,
                        verbose_name="Area Name",
                    ),
                ),
                (
                    "area_type",
                    models.CharField(
                        choices=[
                            ("aerodrome", "Aerodrome/Airport"),
                            ("controlled_airspace", "Controlled Airspace"),
                            ("restricted_area", "Restricted Area"),
                            ("danger_area", "Danger Area"),
                            ("prohibited_area", "Prohibited Area"),
                            ("military_area", "Military Operations Area"),
                            ("national_park", "National Park"),
                            ("populated_area", "Populated Area"),
                            ("emergency_area", "Emergency Operations Area"),
                            ("training_area", "Training Area"),
                            ("commercial_area", "Commercial Operations Area"),
                            ("research_area", "Research Area"),
                        ],
                        help_text="Type of operational area",
                        max_length=20,
                        verbose_name="Area Type",
                    ),
                ),
                (
                    "center_latitude",
                    models.DecimalField(
                        decimal_places=7,
                        help_text="Center latitude in decimal degrees",
                        max_digits=10,
                        verbose_name="Center Latitude",
                    ),
                ),
                (
                    "center_longitude",
                    models.DecimalField(
                        decimal_places=7,
                        help_text="Center longitude in decimal degrees",
                        max_digits=10,
                        verbose_name="Center Longitude",
                    ),
                ),
                (
                    "radius_nautical_miles",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Area radius in nautical miles (for circular areas)",
                        max_digits=8,
                        null=True,
                        verbose_name="Radius (Nautical Miles)",
                    ),
                ),
                (
                    "boundary_geojson",
                    models.JSONField(
                        blank=True,
                        help_text="Precise boundary definition in GeoJSON format",
                        null=True,
                        verbose_name="Boundary GeoJSON",
                    ),
                ),
                (
                    "floor_altitude_amsl",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Area floor altitude above mean sea level",
                        null=True,
                        verbose_name="Floor Altitude AMSL (feet)",
                    ),
                ),
                (
                    "ceiling_altitude_amsl",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Area ceiling altitude above mean sea level",
                        null=True,
                        verbose_name="Ceiling Altitude AMSL (feet)",
                    ),
                ),
                (
                    "floor_height_agl",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Area floor height above ground level",
                        null=True,
                        verbose_name="Floor Height AGL (feet)",
                    ),
                ),
                (
                    "ceiling_height_agl",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Area ceiling height above ground level",
                        null=True,
                        verbose_name="Ceiling Height AGL (feet)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("temporary", "Temporary"),
                            ("permanent", "Permanent"),
                        ],
                        default="active",
                        help_text="Current status of operational area",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "rpa_operations_permitted",
                    models.BooleanField(
                        default=True,
                        help_text="RPA operations are permitted in this area",
                        verbose_name="RPA Operations Permitted",
                    ),
                ),
                (
                    "authorization_required",
                    models.BooleanField(
                        default=False,
                        help_text="Special authorization required for operations",
                        verbose_name="Authorization Required",
                    ),
                ),
                (
                    "effective_from",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date/time area restrictions become effective",
                        null=True,
                        verbose_name="Effective From",
                    ),
                ),
                (
                    "effective_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date/time area restrictions expire",
                        null=True,
                        verbose_name="Effective Until",
                    ),
                ),
                (
                    "controlling_authority",
                    models.CharField(
                        help_text="Authority responsible for this airspace area",
                        max_length=100,
                        verbose_name="Controlling Authority",
                    ),
                ),
                (
                    "contact_frequency",
                    models.CharField(
                        blank=True,
                        help_text="Radio frequency for area coordination",
                        max_length=20,
                        verbose_name="Contact Frequency",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone number for area coordination",
                        max_length=20,
                        verbose_name="Contact Phone",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of area and operational considerations",
                        verbose_name="Description",
                    ),
                ),
                (
                    "operational_notes",
                    models.TextField(
                        blank=True,
                        help_text="Special operational notes and considerations",
                        verbose_name="Operational Notes",
                    ),
                ),
                (
                    "casa_reference",
                    models.CharField(
                        blank=True,
                        help_text="CASA NOTAM, AIP or other reference",
                        max_length=100,
                        verbose_name="CASA Reference",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "airspace_class",
                    models.ForeignKey(
                        help_text="Airspace classification for this area",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="airspace.airspaceclass",
                        verbose_name="Airspace Class",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operational Area",
                "verbose_name_plural": "Operational Areas",
                "ordering": ["area_id"],
            },
        ),
    ]
