# Generated by Django 5.2.7 on 2025-10-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircrafttype',
            name='casa_approval_reference',
            field=models.CharField(
                blank=True,
                help_text='CASA approval or exemption reference',
                max_length=100,
                verbose_name='CASA Approval Reference',
            ),
        ),
        migrations.AddField(
            model_name='aircrafttype',
            name='certification_required',
            field=models.BooleanField(
                default=True,
                help_text='Aircraft requires CASA certification',
                verbose_name='Certification Required',
            ),
        ),
        migrations.AddField(
            model_name='aircrafttype',
            name='endurance_hours',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Maximum flight endurance in hours',
                max_digits=5,
                null=True,
                verbose_name='Endurance (hours)',
            ),
        ),
        migrations.AddField(
            model_name='aircrafttype',
            name='insurance_requirements',
            field=models.TextField(
                blank=True,
                help_text='Insurance coverage requirements',
                verbose_name='Insurance Requirements',
            ),
        ),
        migrations.AddField(
            model_name='aircrafttype',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text='Aircraft type is active and available for selection',
                verbose_name='Active',
            ),
        ),
        migrations.AddField(
            model_name='aircrafttype',
            name='maintenance_requirements',
            field=models.TextField(
                blank=True,
                help_text='Maintenance requirements and schedules',
                verbose_name='Maintenance Requirements',
            ),
        ),
        migrations.AddField(
            model_name='aircrafttype',
            name='operational_limitations',
            field=models.TextField(
                blank=True,
                help_text='Operational limitations and restrictions',
                verbose_name='Operational Limitations',
            ),
        ),
        migrations.AddField(
            model_name='aircrafttype',
            name='payload_capacity',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Maximum payload capacity in kilograms',
                max_digits=6,
                null=True,
                verbose_name='Payload Capacity (kg)',
            ),
        ),
        migrations.AddField(
            model_name='aircrafttype',
            name='training_requirements',
            field=models.TextField(
                blank=True,
                help_text='Training requirements for operators',
                verbose_name='Training Requirements',
            ),
        ),
        migrations.AddField(
            model_name='aircrafttype',
            name='typical_cruise_speed',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Typical cruise speed in knots',
                null=True,
                verbose_name='Typical Cruise Speed (knots)',
            ),
        ),
    ]
