# Generated by Django 5.2.7 on 2025-10-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0002_aircrafttype_casa_approval_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='current_flight_hours',
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                editable=False,
                help_text='Total accumulated flight hours (auto-calculated from flight logs)',
                max_digits=10,
                verbose_name='Current Flight Hours',
            ),
        ),
    ]
