# Generated by Django 5.2.7 on 2025-10-20 09:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clientprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'ordering': ['company_name', 'user__last_name'], 'verbose_name': 'Client Profile', 'verbose_name_plural': 'Client Profiles'},
        ),
        migrations.AlterModelOptions(
            name='operatorcertificate',
            options={'ordering': ['-issue_date'], 'verbose_name': 'Operator Certificate', 'verbose_name_plural': 'Operator Certificates'},
        ),
        migrations.AlterModelOptions(
            name='pilotprofile',
            options={'ordering': ['role', 'user__last_name', 'user__first_name'], 'verbose_name': 'Pilot Profile', 'verbose_name_plural': 'Pilot Profiles'},
        ),
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'Staff Profile', 'verbose_name_plural': 'Staff Profiles'},
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='abn',
            field=models.CharField(blank=True, help_text='Australian Business Number', max_length=20, null=True, verbose_name='ABN'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='payment_terms',
            field=models.PositiveIntegerField(default=30, help_text='Payment terms in days'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('prospect', 'Prospect'), ('suspended', 'Suspended')], default='prospect', max_length=20),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='operatorcertificate',
            name='casa_operator_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CASA Operator Number'),
        ),
        migrations.AddField(
            model_name='operatorcertificate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='operatorcertificate',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='operatorcertificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pilotprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pilotprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='hire_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='account_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to='accounts.staffprofile'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='address',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='contact_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='industry',
            field=models.CharField(blank=True, choices=[('agriculture', 'Agriculture'), ('construction', 'Construction'), ('energy', 'Energy & Utilities'), ('entertainment', 'Entertainment & Media'), ('environmental', 'Environmental'), ('insurance', 'Insurance'), ('mining', 'Mining'), ('real_estate', 'Real Estate'), ('security', 'Security & Surveillance'), ('surveying', 'Surveying & Mapping'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='photo_id',
            field=models.ImageField(blank=True, null=True, upload_to='client_ids/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operatorcertificate',
            name='reoc_number',
            field=models.CharField(help_text='Remote Operator Certificate Number', max_length=50, unique=True, verbose_name='REOC Number'),
        ),
        migrations.AlterField(
            model_name='pilotprofile',
            name='address',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pilotprofile',
            name='arn',
            field=models.CharField(help_text='Aviation Reference Number', max_length=20, unique=True, verbose_name='ARN Number'),
        ),
        migrations.AlterField(
            model_name='pilotprofile',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('on_mission', 'On Mission'), ('unavailable', 'Unavailable'), ('maintenance', 'Equipment Maintenance'), ('training', 'In Training')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='pilotprofile',
            name='certifications',
            field=models.TextField(blank=True, help_text='List additional certifications'),
        ),
        migrations.AlterField(
            model_name='pilotprofile',
            name='contact_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='pilotprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='pilotprofile',
            name='photo_id',
            field=models.ImageField(blank=True, null=True, upload_to='pilot_ids/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='pilotprofile',
            name='repl_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='REPL Expiry Date'),
        ),
        migrations.AlterField(
            model_name='pilotprofile',
            name='repl_number',
            field=models.CharField(blank=True, help_text='Remote Pilot License Number', max_length=20, null=True, verbose_name='REPL Number'),
        ),
        migrations.AlterField(
            model_name='pilotprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='address',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='contact_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(choices=[('operations', 'Operations'), ('admin', 'Administration'), ('hr', 'Human Resources'), ('finance', 'Finance'), ('technical', 'Technical'), ('sales', 'Sales & Marketing')], max_length=100),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='photo_id',
            field=models.ImageField(blank=True, null=True, upload_to='staff_ids/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
