# Generated by Django 5.2.7 on 2025-10-21 09:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_clientprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("staff", "Staff Member"),
                    ("client", "Client"),
                    ("pilot", "Pilot"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="CompanyContactDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legal_entity_name",
                    models.CharField(
                        help_text="Official registered legal name of the company",
                        max_length=200,
                        verbose_name="Name of Legal Entity",
                    ),
                ),
                (
                    "trading_name",
                    models.CharField(
                        blank=True,
                        help_text="Business trading name (if different from legal name)",
                        max_length=200,
                        verbose_name="Trading Name",
                    ),
                ),
                (
                    "registered_office_address",
                    models.TextField(
                        help_text="Full registered office address including postcode",
                        verbose_name="Registered Office Address",
                    ),
                ),
                (
                    "arn",
                    models.CharField(
                        help_text="Aviation Reference Number",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="ARN must be 6-20 alphanumeric characters",
                                regex="^[A-Z0-9]{6,20}$",
                            )
                        ],
                        verbose_name="ARN",
                    ),
                ),
                (
                    "abn",
                    models.CharField(
                        help_text="Australian Business Number",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="ABN must be 11 digits", regex="^\\d{11}$"
                            )
                        ],
                        verbose_name="ABN",
                    ),
                ),
                (
                    "operational_hq_address",
                    models.TextField(
                        help_text="Physical address of operational headquarters",
                        verbose_name="Operational Headquarters Address",
                    ),
                ),
                (
                    "operational_hq_phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Operations Headquarters Phone",
                    ),
                ),
                (
                    "operational_hq_email",
                    models.EmailField(
                        help_text="Main operational contact email",
                        max_length=254,
                        verbose_name="Operational Headquarters Email",
                    ),
                ),
                (
                    "organizational_overview",
                    models.TextField(
                        default="{Legal Entity Name} is an entity that holds a remotely piloted aircraft operator's certificate (ReOC) to conduct aerial work activities in remotely piloted aircraft systems (RPAS). {Legal Entity Name} specialises in aerial survey operations over mine sites utilising the RPA listed in operational documentation. Remote pilots and ground crew are employed on a full-time, part-time or casual basis depending on demand and level of activity. Maintenance is subcontracted to various organisations as required.",
                        help_text="Description of the company's operations and specialties",
                        verbose_name="Organisational Overview",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated these details",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Contact Details",
                "verbose_name_plural": "Company Contact Details",
            },
        ),
    ]
