# Generated by Django 5.2.7 on 2025-10-21 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_role_companycontactdetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyPersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chief_remote_pilot_approved_date",
                    models.DateField(
                        blank=True,
                        help_text="Date approved by CASA for this key position",
                        null=True,
                        verbose_name="Chief Remote Pilot Approval Date",
                    ),
                ),
                (
                    "maintenance_controller_approved_date",
                    models.DateField(
                        blank=True,
                        help_text="Date approved by CASA for this key position",
                        null=True,
                        verbose_name="Maintenance Controller Approval Date",
                    ),
                ),
                (
                    "ceo_approved_date",
                    models.DateField(
                        blank=True,
                        help_text="Date approved by CASA for this key position",
                        null=True,
                        verbose_name="CEO Approval Date",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ceo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select from existing staff profiles - must be authorized CEO",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ceo_assignments",
                        to="accounts.staffprofile",
                        verbose_name="Chief Executive Officer",
                    ),
                ),
                (
                    "chief_remote_pilot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select from existing pilot profiles - must be CASA approved",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chief_remote_pilot_assignments",
                        to="accounts.pilotprofile",
                        verbose_name="Chief Remote Pilot",
                    ),
                ),
                (
                    "maintenance_controller",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select from existing staff profiles - must be qualified for maintenance control",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_controller_assignments",
                        to="accounts.staffprofile",
                        verbose_name="Maintenance Controller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Key Personnel",
                "verbose_name_plural": "Key Personnel",
            },
        ),
    ]
