# Generated by Django 5.2.7 on 2025-10-26 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_keypersonnel'),
        ('core', '0005_add_australian_compliance_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'code',
                    models.CharField(
                        help_text='Unique code for certificate type (e.g., REPL, ARN, WHS)',
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Full name of the certificate', max_length=100
                    ),
                ),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('pilot', 'Pilot Certificates'),
                            ('staff', 'Staff Certificates'),
                            ('maintenance', 'Maintenance Certificates'),
                            ('safety', 'Safety Certificates'),
                            ('training', 'Training Certificates'),
                        ],
                        help_text='Certificate category',
                        max_length=20,
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        help_text='Detailed description of certificate requirements and scope'
                    ),
                ),
                (
                    'validity_period_months',
                    models.IntegerField(
                        default=0,
                        help_text='Certificate validity in months (0 = permanent)',
                    ),
                ),
                (
                    'is_mandatory',
                    models.BooleanField(
                        default=False,
                        help_text='Is this certificate mandatory for the role?',
                    ),
                ),
                (
                    'issuing_authority',
                    models.CharField(
                        help_text='Standard issuing authority (e.g., CASA, WorkSafe)',
                        max_length=100,
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Is this certificate type currently active?',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificate Type',
                'verbose_name_plural': 'Certificate Types',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PersonalCertificate',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'certificate_number',
                    models.CharField(
                        help_text='Official certificate number', max_length=50
                    ),
                ),
                (
                    'issue_date',
                    models.DateField(help_text='Date certificate was issued'),
                ),
                (
                    'expiry_date',
                    models.DateField(
                        blank=True,
                        help_text='Date certificate expires (leave blank for permanent)',
                        null=True,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('valid', 'Valid'),
                            ('expired', 'Expired'),
                            ('suspended', 'Suspended'),
                            ('revoked', 'Revoked'),
                            ('pending', 'Pending Approval'),
                        ],
                        default='valid',
                        max_length=20,
                    ),
                ),
                (
                    'issuing_authority',
                    models.CharField(
                        help_text='Organization that issued this certificate',
                        max_length=100,
                    ),
                ),
                (
                    'issuing_officer',
                    models.CharField(
                        blank=True,
                        help_text='Officer who signed the certificate',
                        max_length=100,
                    ),
                ),
                (
                    'certificate_document',
                    models.FileField(
                        blank=True,
                        help_text='Scanned copy of certificate',
                        null=True,
                        upload_to='certificates/%Y/%m/',
                    ),
                ),
                (
                    'conditions',
                    models.TextField(
                        blank=True,
                        help_text='Any conditions or restrictions on this certificate',
                    ),
                ),
                (
                    'notes',
                    models.TextField(
                        blank=True, help_text='Additional notes about this certificate'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'certificate_type',
                    models.ForeignKey(
                        help_text='Type of certificate',
                        on_delete=django.db.models.deletion.PROTECT,
                        to='accounts.certificatetype',
                    ),
                ),
                (
                    'pilot',
                    models.ForeignKey(
                        blank=True,
                        help_text='Pilot who holds this certificate',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='certificates',
                        to='accounts.pilotprofile',
                    ),
                ),
                (
                    'related_training',
                    models.ForeignKey(
                        blank=True,
                        help_text='Training record that led to this certificate (if applicable)',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='core.trainingregister',
                    ),
                ),
                (
                    'staff',
                    models.ForeignKey(
                        blank=True,
                        help_text='Staff member who holds this certificate',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='certificates',
                        to='accounts.staffprofile',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Personal Certificate',
                'verbose_name_plural': 'Personal Certificates',
                'ordering': ['-issue_date'],
                'unique_together': {
                    ('pilot', 'certificate_type', 'certificate_number'),
                    ('staff', 'certificate_type', 'certificate_number'),
                },
            },
        ),
    ]
