# Generated by Django 5.2.7 on 2025-10-26 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_certificate_models'),
        ('flight_operations', '0002_remove_mission_risk_assessment_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionAssignment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'role',
                    models.CharField(
                        choices=[
                            ('pilot', 'Remote Pilot'),
                            ('observer', 'Aircraft Observer'),
                            ('safety_officer', 'Safety Officer'),
                            ('technical_lead', 'Technical Lead'),
                            ('ground_crew', 'Ground Crew'),
                            ('coordinator', 'Mission Coordinator'),
                            ('backup_pilot', 'Backup Pilot'),
                        ],
                        help_text='Role in the mission',
                        max_length=20,
                        verbose_name='Role',
                    ),
                ),
                (
                    'is_primary',
                    models.BooleanField(
                        default=False,
                        help_text='Primary person for this role',
                        verbose_name='Primary Assignment',
                    ),
                ),
                (
                    'notes',
                    models.TextField(
                        blank=True,
                        help_text='Additional notes about this assignment',
                        verbose_name='Assignment Notes',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'mission',
                    models.ForeignKey(
                        help_text='Mission being staffed',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='crew_assignments',
                        to='flight_operations.mission',
                        verbose_name='Mission',
                    ),
                ),
                (
                    'pilot',
                    models.ForeignKey(
                        blank=True,
                        help_text='Assigned pilot',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='accounts.pilotprofile',
                        verbose_name='Pilot',
                    ),
                ),
                (
                    'staff_member',
                    models.ForeignKey(
                        blank=True,
                        help_text='Assigned staff member',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='accounts.staffprofile',
                        verbose_name='Staff Member',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Mission Assignment',
                'verbose_name_plural': 'Mission Assignments',
                'ordering': ['role', '-is_primary'],
                'unique_together': {
                    ('mission', 'pilot', 'role'),
                    ('mission', 'staff_member', 'role'),
                },
            },
        ),
    ]
