# Generated by Django 5.2.7 on 2025-10-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_operations', '0004_add_dual_flight_plan_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsafetyassessment',
            name='review_date',
            field=models.DateField(
                blank=True,
                help_text='Date for periodic JSA review as required for continuous improvement and compliance audit trail',
                null=True,
                verbose_name='JSA Review Date',
            ),
        ),
    ]
