# Generated by Django 5.2.7 on 2025-10-27 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_australian_compliance_fields'),
        ('flight_operations', '0005_add_jsa_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsafetyassessment',
            name='created_from_sop_step',
            field=models.ForeignKey(
                blank=True,
                help_text='SOP procedure step that triggered this JSA creation (e.g., Step 2 of Flight Operations SOP)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='core.sopprocedurestep',
                verbose_name='Created from SOP Step',
            ),
        ),
        migrations.AddField(
            model_name='jobsafetyassessment',
            name='creation_context',
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the operational context that triggered this JSA (e.g., 'Created during Step 2 of Flight Operations SOP for Mission ABC123')",
                verbose_name='JSA Creation Context',
            ),
        ),
        migrations.AddField(
            model_name='jobsafetyassessment',
            name='creation_context_notes',
            field=models.TextField(
                blank=True,
                help_text='Additional context about why and how this JSA was created (operational trigger, specific requirements, etc.)',
                verbose_name='Creation Context Notes',
            ),
        ),
        migrations.AddField(
            model_name='jobsafetyassessment',
            name='related_aircraft_flight_plan',
            field=models.ForeignKey(
                blank=True,
                help_text='Aircraft flight plan that triggered this JSA creation',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='jsa_aircraft_plans',
                to='flight_operations.aircraftflightplan',
                verbose_name='Related Aircraft Flight Plan',
            ),
        ),
        migrations.AddField(
            model_name='jobsafetyassessment',
            name='related_drone_flight_plan',
            field=models.ForeignKey(
                blank=True,
                help_text='Drone flight plan that triggered this JSA creation',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='jsa_drone_plans',
                to='flight_operations.droneflightplan',
                verbose_name='Related Drone Flight Plan',
            ),
        ),
        migrations.AddField(
            model_name='jobsafetyassessment',
            name='related_flight_plan',
            field=models.ForeignKey(
                blank=True,
                help_text='Flight plan associated with this JSA if created during flight planning process',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='jsa_flight_plans',
                to='flight_operations.flightplan',
                verbose_name='Related Flight Plan',
            ),
        ),
        migrations.AddField(
            model_name='jobsafetyassessment',
            name='related_legacy_flight_plan',
            field=models.ForeignKey(
                blank=True,
                help_text='Legacy flight plan that triggered this JSA creation',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='jsa_legacy_plans',
                to='flight_operations.flightplan',
                verbose_name='Related Legacy Flight Plan',
            ),
        ),
        migrations.AddField(
            model_name='jobsafetyassessment',
            name='sop_reference',
            field=models.ForeignKey(
                blank=True,
                help_text='Standard Operating Procedure that required this JSA',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='core.standardoperatingprocedure',
                verbose_name='Related SOP',
            ),
        ),
        migrations.AddField(
            model_name='jobsafetyassessment',
            name='sop_step_number',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Specific SOP step that triggered JSA creation (e.g., Step 2 of Flight Operations SOP)',
                null=True,
                verbose_name='SOP Step Number',
            ),
        ),
    ]
