# Generated by Django 5.2.7 on 2025-10-28 10:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_certificate_models'),
        ('aircraft', '0003_auto_calculate_flight_hours'),
        ('flight_operations', '0006_add_jsa_creation_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsafetyassessment',
            name='related_flight_plan',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='flight_plan',
        ),
        migrations.RemoveField(
            model_name='jobsafetyassessment',
            name='related_legacy_flight_plan',
        ),
        migrations.AlterModelOptions(
            name='droneflightplan',
            options={
                'ordering': ['-planned_departure_time'],
                'verbose_name': 'Flight Plan',
                'verbose_name_plural': 'Flight Plans',
            },
        ),
        migrations.AddField(
            model_name='droneflightplan',
            name='actual_landing_time',
            field=models.DateTimeField(
                blank=True,
                help_text='Actual flight landing time',
                null=True,
                verbose_name='Actual Landing Time',
            ),
        ),
        migrations.AddField(
            model_name='droneflightplan',
            name='aircraft',
            field=models.ForeignKey(
                default=1,
                help_text='Aircraft for this flight',
                on_delete=django.db.models.deletion.PROTECT,
                to='aircraft.aircraft',
                verbose_name='Aircraft',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='droneflightplan',
            name='departure_latitude',
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text='Departure latitude in decimal degrees',
                max_digits=10,
                null=True,
                verbose_name='Departure Latitude',
            ),
        ),
        migrations.AddField(
            model_name='droneflightplan',
            name='departure_location',
            field=models.CharField(
                blank=True,
                help_text='Departure location description',
                max_length=200,
                null=True,
                verbose_name='Departure Location',
            ),
        ),
        migrations.AddField(
            model_name='droneflightplan',
            name='departure_longitude',
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text='Departure longitude in decimal degrees',
                max_digits=10,
                null=True,
                verbose_name='Departure Longitude',
            ),
        ),
        migrations.AddField(
            model_name='droneflightplan',
            name='pilot_in_command',
            field=models.ForeignKey(
                default=1,
                help_text='Remote pilot in command',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='commanded_flights',
                to='accounts.pilotprofile',
                verbose_name='Pilot in Command',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='droneflightplan',
            name='planned_altitude_agl',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Planned operating altitude above ground level',
                null=True,
                validators=[django.core.validators.MaxValueValidator(400)],
                verbose_name='Planned Altitude AGL (feet)',
            ),
        ),
        migrations.AddField(
            model_name='droneflightplan',
            name='planned_weather_check_time',
            field=models.DateTimeField(
                blank=True,
                help_text='When weather will be checked before flight',
                null=True,
                verbose_name='Planned Weather Check Time',
            ),
        ),
        migrations.AddField(
            model_name='droneflightplan',
            name='remote_pilot_observer',
            field=models.ForeignKey(
                blank=True,
                help_text='Observer pilot (if required)',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='observed_flights',
                to='accounts.pilotprofile',
                verbose_name='Remote Pilot Observer',
            ),
        ),
        migrations.AddField(
            model_name='droneflightplan',
            name='route_waypoints',
            field=models.JSONField(
                blank=True,
                help_text='Flight route waypoints in JSON format',
                null=True,
                verbose_name='Route Waypoints',
            ),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='aircraft_flight_plan',
            field=models.OneToOneField(
                blank=True,
                help_text='Associated aircraft flight plan',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='flight_operations.aircraftflightplan',
                verbose_name='Aircraft Flight Plan',
            ),
        ),
        migrations.AddField(
            model_name='flightlog',
            name='drone_flight_plan',
            field=models.OneToOneField(
                blank=True,
                help_text='Associated drone flight plan',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='flight_operations.droneflightplan',
                verbose_name='Drone Flight Plan',
            ),
        ),
        migrations.AlterField(
            model_name='aircraftflightplan',
            name='aircraft',
            field=models.ForeignKey(
                blank=True,
                help_text='Aircraft for this flight',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='base_flight_plans',
                to='aircraft.aircraft',
                verbose_name='Aircraft',
            ),
        ),
        migrations.AlterField(
            model_name='aircraftflightplan',
            name='pilot_in_command',
            field=models.ForeignKey(
                blank=True,
                help_text='Pilot in command for this flight',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='aircraft_commanded_flights',
                to='accounts.pilotprofile',
                verbose_name='Pilot in Command',
            ),
        ),
        migrations.AlterField(
            model_name='droneflightplan',
            name='drone',
            field=models.ForeignKey(
                help_text='Drone/RPA for this flight',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='drone_flight_plans',
                to='aircraft.aircraft',
                verbose_name='Drone/RPA',
            ),
        ),
        migrations.AlterField(
            model_name='droneflightplan',
            name='flight_plan_id',
            field=models.CharField(
                help_text='Unique flight plan identifier',
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Format: FPL-YYYY-XXXXXX', regex='^FPL-\\d{4}-\\d{6}$'
                    )
                ],
                verbose_name='Flight Plan ID',
            ),
        ),
        migrations.AlterField(
            model_name='droneflightplan',
            name='flight_type',
            field=models.CharField(
                choices=[
                    ('line_of_sight', 'Visual Line of Sight (VLOS)'),
                    ('extended_vlos', 'Extended Visual Line of Sight (EVLOS)'),
                    ('beyond_vlos', 'Beyond Visual Line of Sight (BVLOS)'),
                    ('night_operations', 'Night Operations'),
                    ('controlled_airspace', 'Controlled Airspace Operations'),
                ],
                help_text='Type of flight operation',
                max_length=20,
                verbose_name='Flight Type',
            ),
        ),
        migrations.AlterField(
            model_name='droneflightplan',
            name='lost_link_procedures',
            field=models.TextField(
                help_text='Procedures if communication link is lost',
                verbose_name='Lost Link Procedures',
            ),
        ),
        migrations.DeleteModel(
            name='FlightPlan',
        ),
    ]
