# Generated by Django 5.2.7 on 2025-10-28 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'flight_operations',
            '0007_remove_jobsafetyassessment_related_flight_plan_and_more',
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsafetyassessment',
            name='created_by',
            field=models.ForeignKey(
                help_text='User who created this JSA',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Created By',
            ),
        ),
    ]
