# Generated by Django 5.2.7 on 2025-10-28 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_certificate_models'),
        ('flight_operations', '0008_jobsafetyassessment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='assigned_pilot',
            field=models.ForeignKey(
                blank=True,
                help_text='Primary pilot assigned to this mission',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_missions',
                to='accounts.pilotprofile',
                verbose_name='Assigned Pilot',
            ),
        ),
        migrations.AddField(
            model_name='mission',
            name='crew_members',
            field=models.ManyToManyField(
                blank=True,
                help_text='Additional crew members assigned to this mission',
                related_name='crew_missions',
                to='accounts.pilotprofile',
                verbose_name='Crew Members',
            ),
        ),
        migrations.AddField(
            model_name='mission',
            name='estimated_duration',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Estimated mission duration in hours',
                max_digits=5,
                null=True,
                verbose_name='Estimated Duration (hours)',
            ),
        ),
        migrations.AddField(
            model_name='mission',
            name='notes',
            field=models.TextField(
                blank=True,
                help_text='Additional notes and operational considerations',
                verbose_name='Additional Notes',
            ),
        ),
        migrations.AddField(
            model_name='mission',
            name='special_requirements',
            field=models.TextField(
                blank=True,
                help_text='Special equipment, permissions, or considerations required',
                verbose_name='Special Requirements',
            ),
        ),
        migrations.AddField(
            model_name='mission',
            name='weather_requirements',
            field=models.TextField(
                blank=True,
                help_text='Specific weather conditions required for this mission',
                verbose_name='Weather Requirements',
            ),
        ),
    ]
