# Generated by Django 5.2.7 on 2025-10-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'flight_operations',
            '0009_mission_assigned_pilot_mission_crew_members_and_more',
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='droneflightplan',
            options={
                'verbose_name': 'Drone Flight Plan',
                'verbose_name_plural': 'Drone Flight Plans',
            },
        ),
        migrations.RemoveField(
            model_name='droneflightplan',
            name='actual_landing_time',
        ),
        migrations.RemoveField(
            model_name='droneflightplan',
            name='aircraft',
        ),
        migrations.RemoveField(
            model_name='droneflightplan',
            name='departure_latitude',
        ),
        migrations.RemoveField(
            model_name='droneflightplan',
            name='departure_location',
        ),
        migrations.RemoveField(
            model_name='droneflightplan',
            name='departure_longitude',
        ),
        migrations.RemoveField(
            model_name='droneflightplan',
            name='pilot_in_command',
        ),
        migrations.RemoveField(
            model_name='droneflightplan',
            name='planned_altitude_agl',
        ),
        migrations.RemoveField(
            model_name='droneflightplan',
            name='planned_weather_check_time',
        ),
        migrations.RemoveField(
            model_name='droneflightplan',
            name='remote_pilot_observer',
        ),
        migrations.RemoveField(
            model_name='droneflightplan',
            name='route_waypoints',
        ),
        migrations.AlterField(
            model_name='aircraftflightplan',
            name='flight_plan_id',
            field=models.CharField(
                blank=True,
                help_text='Unique flight plan identifier (auto-generated)',
                max_length=20,
                unique=True,
                verbose_name='Flight Plan ID',
            ),
        ),
        migrations.AlterField(
            model_name='droneflightplan',
            name='flight_plan_id',
            field=models.CharField(
                blank=True,
                help_text='Unique flight plan identifier (auto-generated)',
                max_length=20,
                unique=True,
                verbose_name='Flight Plan ID',
            ),
        ),
        migrations.AlterField(
            model_name='droneflightplan',
            name='flight_type',
            field=models.CharField(
                choices=[
                    ('line_of_sight', 'Visual Line of Sight (VLOS)'),
                    ('extended_vlos', 'Extended Visual Line of Sight (EVLOS)'),
                    ('beyond_vlos', 'Beyond Visual Line of Sight (BVLOS)'),
                    ('night_operations', 'Night Operations'),
                    ('controlled_airspace', 'Controlled Airspace Operations'),
                ],
                help_text='Type of RPAS operation',
                max_length=20,
                verbose_name='Flight Type',
            ),
        ),
        migrations.AlterField(
            model_name='droneflightplan',
            name='lost_link_procedures',
            field=models.TextField(
                help_text='Procedures if communication link is lost with RPA',
                verbose_name='Lost Link Procedures',
            ),
        ),
        migrations.AlterField(
            model_name='droneflightplan',
            name='operating_area_coordinates',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Polygon boundary of operating area (optional - use Operational Area relationship when possible)',
                verbose_name='Operating Area Coordinates',
            ),
        ),
        migrations.AlterField(
            model_name='droneflightplan',
            name='waypoints',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='GPS coordinates for automated flight path',
                verbose_name='Waypoints',
            ),
        ),
    ]
