# Generated by Django 5.2.7 on 2025-10-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_operations', '0010_alter_droneflightplan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraftflightplan',
            name='estimated_flight_time',
        ),
        migrations.RemoveField(
            model_name='droneflightplan',
            name='estimated_flight_time',
        ),
        migrations.AddField(
            model_name='aircraftflightplan',
            name='estimated_flight_time_minutes',
            field=models.PositiveIntegerField(
                default=30,
                help_text='Estimated flight duration in minutes (e.g., 30 for 30 minutes)',
                verbose_name='Estimated Flight Time (minutes)',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='droneflightplan',
            name='estimated_flight_time_minutes',
            field=models.PositiveIntegerField(
                default=10,
                help_text='Estimated flight duration in minutes (e.g., 30 for 30 minutes)',
                verbose_name='Estimated Flight Time (minutes)',
            ),
            preserve_default=False,
        ),
    ]
