# Generated by Django 5.2.7 on 2025-10-22 10:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0005_keypersonnel"),
        ("aircraft", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for incident type",
                        max_length=100,
                        verbose_name="Incident Type Name",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("aircraft_failure", "Aircraft System Failure"),
                            ("pilot_error", "Pilot Error"),
                            ("weather", "Weather Related"),
                            ("airspace_infringement", "Airspace Infringement"),
                            ("collision_risk", "Collision Risk"),
                            ("ground_impact", "Ground Impact/Crash"),
                            ("lost_link", "Lost Communication Link"),
                            ("flyaway", "Aircraft Flyaway"),
                            ("battery_failure", "Battery/Power Failure"),
                            ("mechanical", "Mechanical Failure"),
                            ("software", "Software/Firmware Issue"),
                            ("maintenance", "Maintenance Related"),
                            ("ground_operations", "Ground Operations"),
                            ("third_party", "Third Party Interference"),
                            ("other", "Other"),
                        ],
                        help_text="CASA incident classification",
                        max_length=30,
                        verbose_name="Incident Category",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                            ("critical", "Critical"),
                        ],
                        help_text="Risk severity classification",
                        max_length=10,
                        verbose_name="Severity Level",
                    ),
                ),
                (
                    "casa_reportable",
                    models.BooleanField(
                        default=False,
                        help_text="Must be reported to CASA under Part 101",
                        verbose_name="CASA Reportable",
                    ),
                ),
                (
                    "reporting_timeframe_hours",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum hours to report to CASA",
                        null=True,
                        verbose_name="Reporting Timeframe (Hours)",
                    ),
                ),
                (
                    "immediate_notification_required",
                    models.BooleanField(
                        default=False,
                        help_text="Requires immediate CASA notification",
                        verbose_name="Immediate Notification Required",
                    ),
                ),
                (
                    "investigation_required",
                    models.BooleanField(
                        default=True,
                        help_text="Requires formal investigation",
                        verbose_name="Investigation Required",
                    ),
                ),
                (
                    "grounding_required",
                    models.BooleanField(
                        default=False,
                        help_text="Aircraft must be grounded pending investigation",
                        verbose_name="Aircraft Grounding Required",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of incident type and criteria",
                        verbose_name="Description",
                    ),
                ),
                (
                    "casa_reference",
                    models.CharField(
                        blank=True,
                        help_text="Relevant CASA regulation or advisory material",
                        max_length=50,
                        verbose_name="CASA Reference",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Incident Type",
                "verbose_name_plural": "Incident Types",
                "ordering": ["severity", "category", "name"],
            },
        ),
        migrations.CreateModel(
            name="IncidentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_id",
                    models.CharField(
                        help_text="Unique incident report identifier",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Format: INC-YYYY-XXXXXX",
                                regex="^INC-\\d{4}-\\d{6}$",
                            )
                        ],
                        verbose_name="Incident ID",
                    ),
                ),
                (
                    "incident_date",
                    models.DateTimeField(
                        help_text="Date and time when incident occurred",
                        verbose_name="Incident Date/Time",
                    ),
                ),
                (
                    "location_description",
                    models.CharField(
                        help_text="Description of incident location",
                        max_length=200,
                        verbose_name="Location Description",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Incident location latitude (decimal degrees)",
                        max_digits=10,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Incident location longitude (decimal degrees)",
                        max_digits=10,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "flight_phase",
                    models.CharField(
                        choices=[
                            ("pre_flight", "Pre-Flight"),
                            ("takeoff", "Takeoff"),
                            ("climb", "Climb"),
                            ("cruise", "Cruise"),
                            ("descent", "Descent"),
                            ("approach", "Approach"),
                            ("landing", "Landing"),
                            ("post_flight", "Post-Flight"),
                            ("ground_ops", "Ground Operations"),
                        ],
                        help_text="Phase of flight when incident occurred",
                        max_length=20,
                        verbose_name="Flight Phase",
                    ),
                ),
                (
                    "flight_hours_on_aircraft",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total flight hours on aircraft at time of incident",
                        max_digits=10,
                        null=True,
                        verbose_name="Flight Hours on Aircraft",
                    ),
                ),
                (
                    "weather_conditions",
                    models.CharField(
                        choices=[
                            ("vmc", "Visual Meteorological Conditions (VMC)"),
                            ("imc", "Instrument Meteorological Conditions (IMC)"),
                            ("marginal", "Marginal Weather"),
                            ("unknown", "Unknown"),
                        ],
                        help_text="Weather conditions at time of incident",
                        max_length=20,
                        verbose_name="Weather Conditions",
                    ),
                ),
                (
                    "wind_speed_knots",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Wind speed in knots",
                        null=True,
                        verbose_name="Wind Speed (knots)",
                    ),
                ),
                (
                    "visibility_meters",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Visibility in meters",
                        null=True,
                        verbose_name="Visibility (meters)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_investigation", "Under Investigation"),
                            ("casa_reported", "Reported to CASA"),
                            ("closed", "Closed"),
                            ("reopened", "Reopened"),
                        ],
                        default="draft",
                        help_text="Current status of incident report",
                        max_length=20,
                        verbose_name="Report Status",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Brief summary of what happened",
                        verbose_name="Incident Summary",
                    ),
                ),
                (
                    "detailed_description",
                    models.TextField(
                        help_text="Detailed description of incident sequence",
                        verbose_name="Detailed Description",
                    ),
                ),
                (
                    "aircraft_damage",
                    models.TextField(
                        blank=True,
                        help_text="Description of any aircraft damage",
                        verbose_name="Aircraft Damage",
                    ),
                ),
                (
                    "property_damage",
                    models.TextField(
                        blank=True,
                        help_text="Description of any property damage",
                        verbose_name="Property Damage",
                    ),
                ),
                (
                    "injuries",
                    models.TextField(
                        blank=True,
                        help_text="Description of any injuries",
                        verbose_name="Injuries",
                    ),
                ),
                (
                    "contributing_factors",
                    models.TextField(
                        help_text="Factors that contributed to the incident",
                        verbose_name="Contributing Factors",
                    ),
                ),
                (
                    "immediate_causes",
                    models.TextField(
                        help_text="Immediate causes of the incident",
                        verbose_name="Immediate Causes",
                    ),
                ),
                (
                    "immediate_actions",
                    models.TextField(
                        help_text="Actions taken immediately after incident",
                        verbose_name="Immediate Actions Taken",
                    ),
                ),
                (
                    "preventive_actions",
                    models.TextField(
                        blank=True,
                        help_text="Actions taken to prevent recurrence",
                        verbose_name="Preventive Actions",
                    ),
                ),
                (
                    "casa_reported",
                    models.BooleanField(
                        default=False,
                        help_text="Incident has been reported to CASA",
                        verbose_name="Reported to CASA",
                    ),
                ),
                (
                    "casa_report_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date/time when reported to CASA",
                        null=True,
                        verbose_name="CASA Report Date",
                    ),
                ),
                (
                    "casa_reference_number",
                    models.CharField(
                        blank=True,
                        help_text="CASA incident reference number",
                        max_length=50,
                        verbose_name="CASA Reference Number",
                    ),
                ),
                (
                    "investigation_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Investigation has been completed",
                        verbose_name="Investigation Completed",
                    ),
                ),
                (
                    "investigation_findings",
                    models.TextField(
                        blank=True,
                        help_text="Summary of investigation findings",
                        verbose_name="Investigation Findings",
                    ),
                ),
                (
                    "investigation_completed_date",
                    models.DateField(
                        blank=True,
                        help_text="Date investigation was completed",
                        null=True,
                        verbose_name="Investigation Completed Date",
                    ),
                ),
                (
                    "follow_up_required",
                    models.BooleanField(
                        default=False,
                        help_text="Requires follow-up actions",
                        verbose_name="Follow-up Required",
                    ),
                ),
                (
                    "follow_up_actions",
                    models.TextField(
                        blank=True,
                        help_text="Required follow-up actions",
                        verbose_name="Follow-up Actions",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aircraft",
                    models.ForeignKey(
                        blank=True,
                        help_text="Aircraft involved in incident (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="aircraft.aircraft",
                        verbose_name="Aircraft Involved",
                    ),
                ),
                (
                    "pilot_in_command",
                    models.ForeignKey(
                        help_text="Remote pilot in command during incident",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.pilotprofile",
                        verbose_name="Pilot in Command",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        help_text="Person who submitted this report",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reported By",
                    ),
                ),
                (
                    "incident_type",
                    models.ForeignKey(
                        help_text="Type of incident that occurred",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="incidents.incidenttype",
                        verbose_name="Incident Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident Report",
                "verbose_name_plural": "Incident Reports",
                "ordering": ["-incident_date", "-created_at"],
            },
        ),
    ]
