name: Dependency Update

on:
  schedule:
    - cron: '0 8 * * 1'  # Weekly on Mondays at 8 AM UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools

    - name: Update requirements
      run: |
        # Backup current requirements
        cp requirements.txt requirements.txt.bak
        cp test_requirements.txt test_requirements.txt.bak
        
        # Update dependencies
        pip-compile --upgrade requirements.in || pip-compile --upgrade requirements.txt
        pip-compile --upgrade test_requirements.in || pip-compile --upgrade test_requirements.txt

    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet requirements.txt test_requirements.txt; then
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request
      if: steps.changes.outputs.has_changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: Weekly dependency updates'
        body: |
          ## 📦 Dependency Updates
          
          This PR contains automated dependency updates.
          
          ### Changes:
          - Updated Python package dependencies
          - Resolved any version conflicts
          
          ### Testing:
          - [ ] All tests pass
          - [ ] No breaking changes detected
          - [ ] Security vulnerabilities addressed
          
          **Auto-generated by GitHub Actions**
        branch: dependency-updates
        delete-branch: true